name: dospace
description: Client library to interact with the DigitalOcean Spaces API. Same
  API as Amazon AWS S3.
version: 0.12.13
homepage: https://github.com/nbspou/dospace
author: NO-BREAK SPACE OÜ <support@no-break.space>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  http: ^0.13.1
  meta: ^1.3.0
  xml: ^5.1.0

dev_dependencies:
  ini: ^2.0.1
  test: ^1.16.8
